### ISSUE TITLE
Age of DGPS data field

### ISSUE THREAD

**Issue by oherrala** [twpayne/go-gpx#12]
I'm investigating issue https://github.com/georust/gpx/issues/21 and found similar issue in go-gpx lib.

GPX specification has `ageofdgpsdata` field (notice the D in there). However, go-gpx crate seems to be using `ageofgpsdata`(notice the missing D).

https://github.com/twpayne/go-gpx/blob/583df318e80072b28e8272bde1255b2955e22ce6/gpx.go#L449

https://github.com/twpayne/go-gpx/blob/583df318e80072b28e8272bde1255b2955e22ce6/gpx.go#L410

What's your opinion about this? My feeling is that this is just unfortunate misspelling while coding.

**Comment by twpayne** [comment]
This is a typo/bug for sure. Thank you for spotting and reporting it :)
