### ISSUE TITLE
Migrate xsd file URI scheme from http to https

### ISSUE THREAD

**Issue by rbrud** [twpayne/go-gpx#35]
According to TopoGraphix, the URI scheme should be https for the URL that references the xsd file:
https://www.topografix.com/gpx_for_developers.asp

_Schema locations can change! Many schemas were originally given http addresses, and are now being redirected to https.
Many Garmin schemas have been redirected to a different server, or don't actually exist at the schemaLocation given in
the GPX file. While this is unfortunate, it should not cause your GPX reader to fail.
Do not hard-code assumptions about the locations or availability of GPX schemas into your implementation._

Consider this a change in order to mitigate any future issues were the http to https redirect rule to be removed.

```
$ curl --head --silent http://www.topografix.com/GPX/1/1/gpx.xsd | grep ^HTTP
HTTP/1.1 301 Moved Permanently
```

```
$ curl --head --silent https://www.topografix.com/GPX/1/1/gpx.xsd | grep ^HTTP
HTTP/2 200
```

I have created pull request #34 to implement this change.

Since the examples needed and update due to the change above, I also took the liberty of upgrading the TopoGraphix version from 1.0 to 1.1 in the read and write example considering that version 1.1 only elements are supported by the go-gpx code stack.

**Comment by twpayne** [comment]
Fixed by @rbrud in #34.
